name: Do Something
on:
  - push
  - workflow_dispatch
  
jobs:
  Do-Something:
    runs-on: ubuntu-latest
    steps:
      - name: Do Stuff
        run: |
          sleep 20
          echo Yeaaaaaaaaaaah
